# config/sidekiq.yml
concurrency: 5
queues:
  - default
  - mailers

timezone: Asia/Kolkata

schedule:
  # fetch_fuel_prices:
  #   cron: "1 0 * * *"   # every day at 12:01 AM
  #   class: "FetchFuelPricesJob"
  new_year_mailer:
    cron: "0 10 1 1 *"
    class: "NewYearGreetingWorker"
redis:
  url: <%= ENV.fetch("REDIS_URL") { "redis://127.0.0.1:6379/0" } %>
