# config/sidekiq.yml
concurrency: 5
queues:
  - default
  - mailers

schedule:
  # fetch_fuel_prices:
  #   cron: "1 0 * * *"   # every day at 12:01 AM
  #   class: "FetchFuelPricesJob"
redis:
  url: <%= ENV.fetch("REDIS_URL") { "redis://127.0.0.1:6379/0" } %>
